version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
     - "3306:3306"
    networks:
      - my-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - my-network
  backend:
    container_name: course-nestjs
    build:
      context: ./course-nestjs
      target: development
    volumes:
      - ./course-nestjs:/app/nestjs_backend/
      - /app/nestjs_backend/node_modules
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - "3800:3800"
    depends_on:
      - db
    networks:
      - my-network
networks:
    my-network:
      driver: bridge